language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# Comando de inicio de teste.
script:
  - python test_dado.py
after script:
notifications:
  recipients:
    - bhyanbrito+github@gmail.com
