BoxLayout:
    orientation:'vertical'

    Button:
        text: 'Histórico'
        on_press: print('Histórico')
        id: historico

    GridLayout:
        cols: 3
        spacing: 20
        padding: [200, 10]

        Button:
            text: 'D4'
            on_press: print('D4')
            id: D4

        Button:
            text: 'D6'
            on_press: print('D6')
            id: D6

        Button:
            text: 'D10'
            on_press: print('D10')
            id: D10

        Button:
            text: 'D12'
            on_press: print('D12')
            id: D12

        Button:
            text: 'D20'
            on_press: print('D20')
            id: D20

        Button:
            text: 'D100'
            on_press: print('D100')
            id: D100

    Button:
        text: 'Dificuldade'
        on_press: print('Dificuldade')
        id: dificuldade

    Button:
        text: 'Bônus'
        on_press: print('Bônus')
        id: bonus

    Button:
        text: 'Rolar'
        on_press: print('Rolar')
        id: rolar
