BoxLayout:
    orientation:'vertical'
    spacing: 20
    padding: [20, 10]

    Button:
        text: 'Histórico'
        on_press: print('Histórico')
        id: historico

    GridLayout:
        cols: 4
        spacing: 20
        padding: [20, 10]

        Label:
            text: 'D2'
        Label:
            text: 'D4'   
        Label:
            text: 'D6'
        Label:
            text: 'D8'

        CheckBox:
            on_press: print('D2')
            id: d2
        CheckBox:
            on_press: print('D4')
            id: d4
        CheckBox:
            on_press: print('D6')
            id: d6
        CheckBox:
            on_press: print('D8')
            id: d8

        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d2
        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d4
        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d6
        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d8

        Label:
            text: 'D10'
        Label:
            text: 'D12'
        Label:
            text: 'D20'
        Label:
            text: 'D100'

        CheckBox:
            on_press: print('D10')
            id: d10
        CheckBox:
            on_press: print('D12')
            id: d12
        CheckBox:
            on_press: print('D20')
            id: d20
        CheckBox:
            on_press: print('D100')
            id: d100

        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d10
        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d12
        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d20
        Spinner:
            text: '0'
            values:('1','2','3','4','5','6','7','8','9','10')
            id: quantidade_d100

    GridLayout:
        cols: 2
        spacing: 20
        padding: [5, 10]

        Button:
            text: 'Dificuldade'
            on_press: print('Dificuldade')
            id: dificuldade

        Button:
            text: 'Bônus'
            on_press: print('Bônus')
            id: bonus
    
    Button:
        text: 'Rolar'
        on_press: print('Rolar')
        id: rolar
